language: python
python:
  - "3.7"
  - "3.8"

services: postgresql

env:
  - DJANGO=2.2.12

before_install:
  - export DJANGO_SETTINGS_MODULE='house.settings'
  - export PYTHONPATH=$HOME/builds/abdulhannan709/house
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r ./requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - coverage run --source='.' manage.py test