language: python
python:
  - "3.7"
  - "3.8"

services: postgresql

env:
  - DJANGO=1.4.1

before_install:
  - export DJANGO_SETTINGS_MODULE=./house.DJANGO_SETTINGS_MODULE
  - export PYTHONPATH=$HOME/builds/abdulhannan709/house
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r ./requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py syncdb --noinput
  - coverage run --source='.' manage.py test